language: objective-c
matrix:
  include:
    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace Ed25519.xcworkspace -scheme Ed25519macOS -configuration Release | xcpretty -c
    - os: osx
      language: generic
      script:
        - swift build
        - swift test

